name: Update Orders on GitHub

on:  
  workflow_dispatch: # Runs manually from GitHub Actions
  push:
    branches:
      - main  # Runs when code is pushed to the main branch

jobs:
  update-orders:
    runs-on: ubuntu-latest  # Use Ubuntu environment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Get the latest code from the repo

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Ensure Node.js is installed

      - name: Install dependencies
        run: npm install  # If you have dependencies, install them here

      - name: Run JavaScript Script
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}  # Load the GitHub Secret
        run: node updateOrders.js  # Run your JavaScript script
